#!/bin/bash

set -x;
set -e;

docker build -t base -f base.Dockerfile .;
docker build -t build -f build.Dockerfile .;

mkdir -p build/wheelhouse;

docker run --rm \
       -v "$(pwd)":/application \
       build;

docker build -t glyph/rproxy .;
